name: "Regression Test - Docker Image"
on:
  workflow_dispatch:
  push:
    paths:
      - '**regression-test-docker-image.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t "webperf-runner:0.0.2" .
    - name: Run it
      run: docker run --cap-add=SYS_ADMIN --rm webperf-runner:0.0.2 python default.py -r -i sites.json
