name: "Regression Test - Google Lighthouse Based Test(s)"
on:
  push:
    paths-ignore:
      - '**.md'
      - 'software-full.json'
      - 'software-sources.json'
      - '**update-software.yml'
      - 'update_software.py'
      - 'SAMPLE-software-rules.json'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                config: ['REVIEW_SHOW_IMPROVEMENTS_ONLY=True,LIGHTHOUSE_USE_API=False']
                version: [1, 4, 5, 8, 10, 22]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
    - name: Setup node (ONLY used for Yellow Lab Tools AND lighthouse)
      uses: actions/setup-node@v4
    - name: Setup lighthouse npm package (ONLY used for lighthouse)
      run: npm install lighthouse
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Setup config (using SAMPLE-config.py as config.py) - LINUX
      run: python .github/workflows/verify_result.py -c ${{ matrix.config }}
    - if: ${{ matrix.os == 'windows-latest' }}
      name: Setup config (using SAMPLE-config.py as config.py) - WINDOWS
      run: python .github\workflows\verify_result.py -c ${{ matrix.config }}
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: RUNNING TEST - LINUX
      run: |
         python default.py -t ${{ matrix.version }} -r -i sites.json -o .github/workflows/testresult-${{ matrix.version }}.json
         python .github/workflows/verify_result.py -t ${{ matrix.version }}
    - if: ${{ matrix.os == 'windows-latest' }}
      name: RUNNING TEST - WINDOWS
      run: |
         python default.py -t ${{ matrix.version }} -r -i sites.json -o .github\workflows\testresult-${{ matrix.version }}.json
         python .github\workflows\verify_result.py -t ${{ matrix.version }}
